- name: injecting a fault
  hosts: control
  vars:
      fault: "isolate_leader"
      run_id: "run1"
  tasks:
    - name: injecting a fault
      become_user: ubuntu
      shell: |
        python3 /mnt/vectorized/tests/fault.inject.py {{ fault }} {{ run_id }}